name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Add the following line to include the additional rule in ESLint
          eslint_additional_args: "--no-ignore --ignore-path .gitignore --ext .js --rule 'no-undef: [2, { \"vars\": \"all\", \"args\": \"after-used\", \"ignoreRestSiblings\": false, \"varsIgnorePattern\": \"chrome\" }]'"
